version: "3.8"

services:
  fastapi-service:
    build: ./backend
    container_name: fastapi-baseline
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '5.0'
          memory: 6G
        reservations:
          cpus: '3.0'
          memory: 4G
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
  frontend-llm-agent:
    build:
      context: ./frontend/llm-agent-megaschool
      dockerfile: Dockerfile
    container_name: frontend-llm-agent
    ports:
      - "8081:80"